twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel
        timeout: 0.5
        priority: 10
      line_follower:
        topic: cmd_vel_follower
        timeout: 0.5
        priority: 20
      joystick:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 100