<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="lidar_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="lidar_link"/>
        <origin xyz="${L_x+L_x_off} 0 ${L_z+L_z_off}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="lidar_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find sevillabot)/meshes/ADDON_Lidar_assy.stl" scale="1.0e-3 1.0e-3 1.0e-3"/>
            </geometry>
            <origin xyz="${-L_x_off} 0 ${-L_z_off}" rpy="0.0 0.0 0.0"/>
            <material name="green" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${L_D/2}" length="${L_h}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision> 

        <xacro:inertial_cylinder mass="${L_mass}" radius="${L_D/2}" length="${L_h}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>

    </link>

    <gazebo reference="lidar_link">
        
        <material>Gazebo/Green</material>

        <sensor name="lidar" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize> true </visualize> <!-- visualize laser rays -->
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>12</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <plugin name="lidar_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument> <!-- topic -->
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>lidar_link</frame_name>
            </plugin>
        </sensor>
    
    </gazebo>

</robot>
