<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- MATERIALS -->
    <!-- white black light_gray dark_gray green blue red yellow orange -->

    <xacro:include filename="materials.xacro" />

    <!-- INERTIAL MACROS -->

    <xacro:include filename="inertial_macros.xacro" />

    <!-- BASE LINK -->

    <link name="base_link">
    </link>

    <!-- BASE_FOOTPRINT LINK -->
    
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_footprint">
    </link>

    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis_link" />
        <origin xyz="${W_x-box_x/2} 0 ${W_z}" />
    </joint>

    <link name="chassis_link">
        <visual>
            <geometry>
            	<mesh filename="file://$(find sevillabot)/meshes/ASSY_sevillabot_base.stl" scale="1.0e-3 1.0e-3 1.0e-3"/>
                <!-- box size="${box_x} ${box_y} ${box_z}" /> -->
            </geometry>
            <origin xyz="${box_x/2} 0 0" rpy="0 0 -${pi/2}"/>
            <material name="white" />
        </visual>

        <collision>
            <geometry>
                <box size="${box_x} ${box_y} ${box_z}" />
            </geometry>
            <origin xyz="${box_x/2} 0 ${box_z/2}" />
        </collision>

        <xacro:inertial_box mass="${box_mass}" x="${box_x}" y="${box_y}" z="${box_z}">
            <origin xyz="${box_x/2} 0 ${box_z/2}" rpy="0 0 0" />
        </xacro:inertial_box>

    </link>

    <gazebo reference="chassis_link">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="0 ${W_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${W_D/2}" length="${W_h}" />
            </geometry>
            <material name="blue" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="${W_D/2}" />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${W_mass}" radius="${W_D/2}" length="${W_h}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>

    </link>

    <gazebo reference="left_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="0 -${W_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${W_D/2}" length="${W_h}" />
            </geometry>
            <material name="blue" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="${W_D/2}" />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${W_mass}" radius="${W_D/2}" length="${W_h}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>

    </link>

    <gazebo reference="right_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${box_x-c_x} 0 ${-c_z}" />
    </joint>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${c_D/2}" />
            </geometry>
            <material name="yellow" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="${c_D/2}" />
            </geometry>
        </collision>

        <xacro:inertial_sphere mass="${c_mass}" radius="${c_D/2}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_sphere>

    </link>

    <gazebo reference="caster_wheel_link">
        <material>Gazebo/Yellow</material>
        <mu1 value="0.0001" />
        <mu2 value="0.0001" />
    </gazebo>


</robot>
